// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5FCDEBGKUQqHnyBu78TuyhTBTJwoAiBQ',
    appId: '1:1000420193068:web:5e16fb41f8fd504077f289',
    messagingSenderId: '1000420193068',
    projectId: 'foody-6247b',
    authDomain: 'foody-6247b.firebaseapp.com',
    storageBucket: 'foody-6247b.appspot.com',
    measurementId: 'G-WXK6RB80VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YlBYX_N1EEYA3rV5XsvtzclxPwAyvxk',
    appId: '1:1000420193068:android:8d2cdd2f74637c8b77f289',
    messagingSenderId: '1000420193068',
    projectId: 'foody-6247b',
    storageBucket: 'foody-6247b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFsnyZqC5Wgsm5ai07cxTSeGq2ePepnFI',
    appId: '1:1000420193068:ios:a7c4b8f9525e8d4b77f289',
    messagingSenderId: '1000420193068',
    projectId: 'foody-6247b',
    storageBucket: 'foody-6247b.appspot.com',
    iosBundleId: 'com.example.easyfoody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsnyZqC5Wgsm5ai07cxTSeGq2ePepnFI',
    appId: '1:1000420193068:ios:b6bc79f72c4abdb377f289',
    messagingSenderId: '1000420193068',
    projectId: 'foody-6247b',
    storageBucket: 'foody-6247b.appspot.com',
    iosBundleId: 'com.example.easyfoody.RunnerTests',
  );
}
